# Generated by Django 5.1.1 on 2024-09-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='year',
            new_name='period',
        ),
    ]
