# Generated by Django 5.1.1 on 2024-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_year_experience_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.IntegerField(max_length=100),
        ),
    ]
